const ROLES = require('../constants/roles');

const defaultUsers = [
  {
    name: 'Admin User',
    email: 'admin@recipe.com',
    password: 'admin123',
    role: ROLES.ADMIN,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    bio: 'Head Culinary Master & System Administrator.',
  },
  {
    name: 'Standard User',
    email: 'user@recipe.com',
    password: 'user123',
    role: ROLES.USER,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    bio: 'Home cook and food enthusiast.',
  },
];

const defaultCategories = [
  {
    name: 'Veg',
    slug: 'veg',
    description: 'Fresh and wholesome vegetarian dishes packed with nutrients and vibrant spices.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
  },
  {
    name: 'Non-Veg',
    slug: 'non-veg',
    description: 'Succulent chicken, mutton, and seafood specialties cooked to perfection.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop',
  },
  {
    name: 'Desserts',
    slug: 'desserts',
    description: 'Decadent sweet treats, traditional Indian mithai, and heavenly desserts.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop',
  },
  {
    name: 'Snacks',
    slug: 'snacks',
    description: 'Crispy finger foods, street food favorites, and quick bite-sized snacks.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
  },
  {
    name: 'Beverages',
    slug: 'beverages',
    description: 'Refreshing drinks, spiced lassis, and herbal infusions.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',
  },
  {
    name: 'Breads',
    slug: 'breads',
    description: 'Soft tandoori naans, crispy parathas, and whole wheat flatbreads.',
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=400&h=300&fit=crop',
  },
];

const defaultRecipes = [
  {
    title: 'Butter Chicken',
    slug: 'butter-chicken',
    description: 'Rich and creamy tomato-based curry with tender chicken pieces, a restaurant-style classic made at home.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
    categoryName: 'Non-Veg',
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 4,
    difficulty: 'Medium',
    ratingAverage: 4.9,
    ratingCount: 145,
    isFeatured: true,
    isPublished: true,
    tags: ['Chicken', 'Curry', 'North Indian', 'Popular'],
    ingredients: [
      { item: 'Chicken Breast / Thighs', qty: '500g', note: 'Cut into bite-sized cubes' },
      { item: 'Heavy Cream', qty: '1/2 cup', note: 'Fresh' },
      { item: 'Tomato Puree', qty: '1.5 cups', note: 'Smooth blend' },
      { item: 'Butter / Ghee', qty: '3 tbsp', note: 'Unsalted' },
      { item: 'Garam Masala & Kasuri Methi', qty: '2 tsp', note: 'Toasted and crushed' },
    ],
    instructions: [
      'Marinate chicken cubes with yogurt, lemon juice, ginger-garlic paste, and spices for 30 minutes.',
      'Sear the marinated chicken in a pan with 1 tbsp butter until lightly charred.',
      'In a separate skillet, melt remaining butter and simmer tomato puree with aromatic spices for 15 minutes.',
      'Blend sauce until silky smooth, stir in heavy cream, fold in seared chicken, and simmer for 10 minutes.',
      'Garnish with kasuri methi and extra cream. Serve hot with Garlic Naan.',
    ],
  },
  {
    title: 'Paneer Tikka',
    slug: 'paneer-tikka',
    description: 'Marinated cottage cheese cubes grilled to perfection with smoky flavors and aromatic spices.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop',
    categoryName: 'Veg',
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    servings: 3,
    difficulty: 'Easy',
    ratingAverage: 4.8,
    ratingCount: 92,
    isFeatured: true,
    isPublished: true,
    tags: ['Paneer', 'Starter', 'Vegetarian', 'Grilled'],
    ingredients: [
      { item: 'Paneer Cubes', qty: '300g', note: 'Fresh and firm' },
      { item: 'Hung Curd / Greek Yogurt', qty: '1/2 cup', note: 'Thick' },
      { item: 'Bell Peppers & Onions', qty: '1 cup', note: 'Square cut' },
      { item: 'Chaat Masala', qty: '1 tsp', note: 'For finishing' },
    ],
    instructions: [
      'Mix hung curd with mustard oil, Kashmiri red chili powder, ginger-garlic paste, and spices.',
      'Coat paneer cubes, bell peppers, and onion squares thoroughly in marinade. Rest for 20 minutes.',
      'Thread paneer and veggies onto skewers and grill at high heat for 10-12 minutes until charred.',
      'Sprinkle chaat masala and lemon juice before serving with mint chutney.',
    ],
  },
  {
    title: 'Hyderabadi Chicken Biryani',
    slug: 'hyderabadi-chicken-biryani',
    description: 'Layered Basmati rice and spiced marinated chicken cooked together for an aromatic, one-pot royal feast.',
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=600&h=400&fit=crop',
    categoryName: 'Non-Veg',
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    servings: 6,
    difficulty: 'Hard',
    ratingAverage: 5.0,
    ratingCount: 210,
    isFeatured: true,
    isPublished: true,
    tags: ['Biryani', 'Rice', 'Royal', 'Hyderabad'],
    ingredients: [
      { item: 'Long-grain Basmati Rice', qty: '2 cups', note: 'Soaked for 30 minutes' },
      { item: 'Marinated Chicken', qty: '750g', note: 'Bone-in pieces' },
      { item: 'Fried Onions (Birista)', qty: '1 cup', note: 'Golden crispy' },
      { item: 'Saffron Milk', qty: '3 tbsp', note: 'Warm milk infused with saffron' },
    ],
    instructions: [
      'Parboil soaked Basmati rice with whole spices until 70% cooked.',
      'Layer marinated raw chicken in a heavy Dutch oven, cover with half fried onions and herbs.',
      'Spread parboiled rice evenly on top, drizzle saffron milk, ghee, and rose water.',
      'Seal lid tightly with dough and cook on Dum (slow steam) for 35 minutes.',
      'Gentle fluff rice and serve hot with Mirchi Ka Salan and Raita.',
    ],
  },
  {
    title: 'Dal Makhani',
    slug: 'dal-makhani',
    description: 'Slow-cooked black lentils in a velvety, butter-infused tomato gravy, a North Indian restaurant favorite.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    categoryName: 'Veg',
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 4,
    difficulty: 'Medium',
    ratingAverage: 4.7,
    ratingCount: 88,
    isFeatured: true,
    isPublished: true,
    tags: ['Dal', 'Lentils', 'Comfort Food', 'Creamy'],
    ingredients: [
      { item: 'Whole Black Gram (Urad Dal)', qty: '1 cup', note: 'Soaked overnight' },
      { item: 'Kidney Beans (Rajma)', qty: '1/4 cup', note: 'Soaked overnight' },
      { item: 'Butter & Cream', qty: '4 tbsp', note: 'Rich finish' },
    ],
    instructions: [
      'Pressure cook soaked urad dal and rajma until melt-in-your-mouth soft.',
      'Prepare a fragrant tempering with butter, cumin, ginger, garlic, and tomato puree.',
      'Combine cooked lentils with tomato tempering and simmer on slow heat for 25 minutes while mashing gently.',
      'Finish with heavy cream and serve hot with Jeera Rice.',
    ],
  },
  {
    title: 'Gulab Jamun',
    slug: 'gulab-jamun',
    description: 'Soft, melt-in-the-mouth fried milk dumplings soaked in cardamom and rose-scented sugar syrup.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop',
    categoryName: 'Desserts',
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 6,
    difficulty: 'Easy',
    ratingAverage: 4.9,
    ratingCount: 160,
    isFeatured: true,
    isPublished: true,
    tags: ['Sweet', 'Dessert', 'Indian Sweet', 'Festive'],
    ingredients: [
      { item: 'Khoya / Mawa', qty: '200g', note: 'Grated' },
      { item: 'All-Purpose Flour (Maida)', qty: '2 tbsp', note: 'Sifted' },
      { item: 'Sugar Syrup Base', qty: '2 cups', note: 'Infused with cardamom & rose' },
    ],
    instructions: [
      'Knead khoya, flour, and pinch of baking powder into a smooth dough without cracking.',
      'Roll into small crack-free balls.',
      'Deep fry in ghee/oil over low flame until golden brown.',
      'Soak immediately in warm fragrant sugar syrup for at least 2 hours.',
    ],
  },
];

const defaultBlogs = [
  {
    title: '10 Essential Spices for Indian Cooking',
    slug: '10-essential-spices-for-indian-cooking',
    excerpt: 'Discover the must-have spices that form the foundation of Indian cuisine and learn how to use them effectively.',
    content: `Spices are the heart and soul of Indian cooking. From fragrant cardamom to warm cumin, understanding how to bloom, toast, and grind whole spices elevates home cooking into an art form.

1. **Cumin Seeds (Jeera)**: Provides an earthy, nutty base note.
2. **Coriander Seeds**: Offers bright, citrusy citrus warmth.
3. **Turmeric Powder (Haldi)**: Gives brilliant golden hue and anti-inflammatory properties.
4. **Garam Masala**: The royal finish of fragrant sweet and pungent whole spices.
5. **Kashmiri Red Chili**: Delivers vibrant red color with mild, pleasant heat.`,
    featuredImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop',
    author: 'Chef Master',
    category: 'Guide',
    tags: ['Spices', 'Cooking Tips', 'Indian Cuisine'],
    isPublished: true,
    publishedAt: new Date(),
  },
  {
    title: 'Healthy Cooking Tips for Beginners',
    slug: 'healthy-cooking-tips-for-beginners',
    excerpt: 'Learn simple techniques to make your meals healthier without compromising on rich taste and flavor.',
    content: `Healthy cooking doesn't mean bland food! By utilizing steam-roasting, cold-pressed oils, and fresh herb finishing, you can build rich depth of flavor with minimal unnecessary saturated fats.`,
    featuredImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop',
    author: 'Chef Master',
    category: 'Health',
    tags: ['Health', 'Nutrition', 'Beginner'],
    isPublished: true,
    publishedAt: new Date(),
  },
];

module.exports = {
  defaultUsers,
  defaultCategories,
  defaultRecipes,
  defaultBlogs,
};
